// glossary.js — proper-noun + terminology control for EN -> zh-TW translation.
// { en, zh }  where zh === "KEEP" means leave the term in English.
// Seeded from demoday-live-translation-spec.md §2.5 + the #32/#10 team data.
// This is the same file the Worker's /api/translate will load in step 3.

export const GLOSSARY = [
  // --- core event / org names ---
  { en: "AppWorks",   zh: "KEEP", note: "never 'Apple Works' / 'AirPods' / '蘋果'" },
  { en: "Wistron",    zh: "緯創", note: "緯創資通" },
  { en: "Demo Day",   zh: "Demo Day", note: "keep in English" },
  { en: "Phison",     zh: "群聯",  note: "群聯電子; KS Pua's company" },
  { en: "KS Pua",     zh: "KEEP", note: "Phison chairman & CEO (潘健成)" },

  // --- terminology: Taiwan usage (zh-TW), not PRC ---
  { en: "accelerator",  zh: "加速器" },
  { en: "fundraising",  zh: "募資" },
  { en: "startup",      zh: "新創",   note: "NOT 初创/创业公司 (PRC usage)" },
  { en: "software",     zh: "軟體",   note: "NOT 软件" },
  { en: "network",      zh: "網路",   note: "NOT 网络" },
  { en: "video",        zh: "影片",   note: "NOT 视频" },
  { en: "AI",           zh: "AI",     note: "or 人工智慧, NOT 人工智能" },
  { en: "founder",      zh: "創辦人",  note: "NOT 创始人" },
  { en: "valuation",    zh: "估值" },
  { en: "round",        zh: "輪",     note: "as in funding round, e.g. A 輪" },

  // --- #32 startups (keep English company names) ---
  { en: "NOTAG KOREA",  zh: "KEEP" },
  { en: "Notifly",      zh: "KEEP", note: "Korean marketing-automation startup (founder Minyong Lee). Brand is 'Notifly', NOT 'Notify' — STT may mishear it. But 'notify'/'notification' as a plain verb/noun = 通知; only render the brand when the company is clearly meant." },
  { en: "Krush",        zh: "KEEP" },
  { en: "Innowave Tech",zh: "KEEP" },
  { en: "LIPS",         zh: "KEEP" },
  { en: "Shieldbase",   zh: "KEEP" },
  { en: "OmniEase AI",  zh: "KEEP" },
  { en: "Pathors",      zh: "KEEP" },
  { en: "Rosary Labs",  zh: "KEEP" },
  { en: "Novo AI",      zh: "KEEP" },
  { en: "Hyarks",       zh: "KEEP" },
  { en: "Arrivl",       zh: "KEEP" },
  { en: "Decisions Lab",zh: "KEEP" },
  { en: "SixSense",     zh: "KEEP" },
  { en: "Refundy",      zh: "KEEP" },

  // --- Wistron #10 startups ---
  { en: "Phasetrum",    zh: "KEEP" },
  { en: "Ruomei",       zh: "KEEP" },
  { en: "GreenBidz",    zh: "KEEP" },
  { en: "CloudStation", zh: "KEEP" },

  // --- presenters (keep names in English) ---
  { en: "Aiden Ung Choi",     zh: "KEEP" },
  { en: "Minyong Lee",        zh: "KEEP" },
  { en: "Stephen Moon",       zh: "KEEP" },
  { en: "Jinsong Xu",         zh: "KEEP" },
  { en: "Luke Liu",           zh: "KEEP" },
  { en: "Diego Rojas",        zh: "KEEP" },
  { en: "Sebastian Wijaya",   zh: "KEEP" },
  { en: "Yu-Chieh Cheng",     zh: "KEEP" },
  { en: "May Law",            zh: "KEEP" },
  { en: "Julien Condamines",  zh: "KEEP" },
  { en: "Juan Herrero Valero",zh: "KEEP" },
  { en: "Ryan Chen",          zh: "KEEP" },
  { en: "Louis Cheung",       zh: "KEEP" },
  { en: "Akanksha Jagwani",   zh: "KEEP" },
  { en: "Jaekyeum Kim",       zh: "KEEP" },
  { en: "Wayne Tsai",         zh: "KEEP" },
  { en: "Owen Lee",           zh: "KEEP" },
  { en: "Jerry Yiu",          zh: "KEEP" },
  { en: "Oumnya Benhassou",   zh: "KEEP" },
  // --- auto-merged from team pitch scripts (build-glossary.mjs); always-on ---
  { en: "Airbnb", zh: "KEEP", note: "Company name, ensure consistent spelling." },
  { en: "AI Agents", zh: "KEEP", note: "Specific term for AI-driven entities, ensure consistent capitalization." },
  { en: "Google AI", zh: "KEEP", note: "Brand name, ensure consistent spelling." },
  { en: "Agent Experience", zh: "KEEP", note: "Specific term contrasting with User Experience, ensure consistent capitalization." },
  { en: "User Experience", zh: "KEEP", note: "Common term but ensure consistent capitalization." },
  { en: "Ryan", zh: "KEEP", note: "Person name, ensure consistent spelling." },
  { en: "KH", zh: "KEEP", note: "Person name, example friend." },
  { en: "Sam", zh: "KEEP", note: "Person name, example friend." },
  { en: "Jamie", zh: "KEEP", note: "Person name, example friend." },
  { en: "Big Tech", zh: "KEEP", note: "Refers to major technology companies." },
  { en: "AI-face-verified", zh: "人工智慧臉部驗證", note: "Specific feature of the app." },
  { en: "Day-7 retention", zh: "第七天留存率", note: "Metric for user retention." },
  { en: "Day-30 retention", zh: "第三十天留存率", note: "Metric for user retention." },
  { en: "Samsung Electronics", zh: "KEEP", note: "Company name." },
  { en: "Amazon", zh: "KEEP", note: "Company name." },
  { en: "Columbia Business School", zh: "KEEP", note: "Institution name." },
  { en: "Aiden", zh: "KEEP", note: "Person name, CEO of NOTAG KOREA." },
  { en: "AI-driven", zh: "人工智慧驅動", note: "Refers to technology powered by artificial intelligence." },
  { en: "NTMS", zh: "KEEP", note: "Acronym for NOTAG's system, should remain in English." },
  { en: "NABI", zh: "KEEP", note: "Name of NOTAG's AI, should remain in English." },
  { en: "agentic AI", zh: "代理人工智慧", note: "Refers to AI that acts as an agent." },
  { en: "B2B", zh: "企業對企業", note: "Business-to-business, a type of commerce transaction." },
  { en: "B2C", zh: "企業對消費者", note: "Business-to-consumer, a type of commerce transaction." },
  { en: "Series B", zh: "B輪融資", note: "A round of financing for a company." },
  { en: "Minyong", zh: "KEEP", note: "Person name, ensure consistent spelling." },
  { en: "Coupang", zh: "KEEP", note: "Company name, ensure consistent spelling." },
  { en: "Naver", zh: "KEEP", note: "Company name, ensure consistent spelling." },
  { en: "Alan", zh: "KEEP", note: "Person name, ensure consistent spelling." },
  { en: "CJ Logistics", zh: "KEEP", note: "Company name, ensure consistent spelling." },
  { en: "Cash Slide", zh: "KEEP", note: "Company name, ensure consistent spelling." },
  { en: "KT Wiz", zh: "KEEP", note: "Baseball team name, ensure consistent spelling." },
  { en: "cart abandoners", zh: "購物車放棄者", note: "Specific term for users who abandon shopping carts." },
  { en: "onboarding journey", zh: "用戶啟動流程", note: "Specific term for user onboarding process." },
  { en: "OmniEase", zh: "KEEP", note: "Company name, ensure consistent capitalization." },
  { en: "Sebastian", zh: "KEEP", note: "Person name, ensure correct spelling." },
  { en: "HS codes", zh: "KEEP", note: "Harmonized System codes, important for trade classification." },
  { en: "DDP", zh: "KEEP", note: "Delivered Duty Paid, a term in international shipping." },
  { en: "Dennis", zh: "KEEP", note: "Person name, ensure correct spelling." },
  { en: "Xiao", zh: "KEEP", note: "Person name, ensure correct spelling." },
  { en: "Link to Windows", zh: "KEEP", note: "Product name, ensure correct capitalization." },
  { en: "Rosary Vision", zh: "KEEP", note: "Product name, ensure consistent capitalization." },
  { en: "May", zh: "KEEP", note: "Person name, ensure consistent capitalization." },
  { en: "Autodesk Revit", zh: "KEEP", note: "Software name, ensure consistent capitalization." },
  { en: "AEC", zh: "KEEP", note: "Acronym for Architecture, Engineering, and Construction, ensure consistent capitalization." },
  { en: "Kuala Lumpur", zh: "吉隆坡", note: "City name, ensure correct translation." },
  { en: "Malaysia", zh: "馬來西亞", note: "Country name, ensure correct translation." },
  { en: "Korea", zh: "韓國", note: "Country name, ensure correct translation." },
  { en: "Vietnam", zh: "越南", note: "Country name, ensure correct translation." },
  { en: "Beta", zh: "KEEP", note: "Software testing phase, ensure consistent capitalization." },
  { en: "pilot", zh: "KEEP", note: "Testing phase, ensure consistent usage." },
  { en: "Jacky", zh: "KEEP", note: "Person name, ensure consistent spelling." },
  { en: "thermal-management", zh: "熱管理", note: "Domain-specific jargon, ensure correct translation." },
  { en: "heat-dissipation", zh: "散熱", note: "Domain-specific jargon, ensure correct translation." },
  { en: "3D printing", zh: "3D 列印", note: "Ensure correct translation and numeral format." },
  { en: "PCB", zh: "KEEP", note: "Printed Circuit Board, commonly used acronym." },
  { en: "光子散熱技術", zh: "光子散熱技術", note: "Photon thermal technology, ensure correct translation." },
  { en: "高雄橋頭科學園區", zh: "高雄橋頭科學園區", note: "Kaohsiung Qiaotou Science Park, ensure correct translation." },
  // --- from MC intro scripts (hosts, sponsors, partner brands, jargon); always-on ---
  { en: "Alyssa Chen", zh: "KEEP", note: "AppWorks host / MC" },
  { en: "Alyssa", zh: "KEEP", note: "AppWorks host (Alyssa Chen)" },
  { en: "HsiChun Tsai", zh: "KEEP", note: "AppWorks Accelerator Program Manager / MC" },
  { en: "HsiChun", zh: "KEEP", note: "AppWorks MC (HsiChun Tsai)" },
  { en: "Michelle", zh: "KEEP", note: "AppWorks MC" },
  { en: "Simon", zh: "KEEP", note: "Wistron MC" },
  { en: "Johnny", zh: "KEEP", note: "MC" },
  { en: "KS", zh: "KEEP", note: "KS Pua, Phison founder; keynote speaker" },
  { en: "Nayul Kim", zh: "KEEP", note: "Co-Founder & CEO, CLIKA" },
  { en: "Nayul", zh: "KEEP", note: "CLIKA CEO (Nayul Kim)" },
  { en: "Ben", zh: "KEEP", note: "CLIKA co-founder; ex-Mobileye" },
  { en: "Brandon", zh: "KEEP", note: "Pathors founder (Yu-Chieh Cheng)" },
  { en: "Jinsong", zh: "KEEP", note: "Innowave founder (Jinsong Xu)" },
  { en: "Luke", zh: "KEEP", note: "LIPS founder (Luke Liu)" },
  { en: "Diego", zh: "KEEP", note: "Shieldbase founder (Diego Rojas)" },
  { en: "Akanksha", zh: "KEEP", note: "SixSense founder (Akanksha Jagwani)" },
  { en: "Juan", zh: "KEEP", note: "Hyarks founder (Juan Herrero)" },
  { en: "Julien", zh: "KEEP", note: "Novo AI founder (Julien Condamines)" },
  { en: "Louis", zh: "KEEP", note: "Decisions Lab founder (Louis Cheung)" },
  { en: "Stephen", zh: "KEEP", note: "Krush founder (Stephen Moon)" },
  { en: "Google Cloud", zh: "KEEP", note: "Demo Day sponsor" },
  { en: "AWS for Startups", zh: "KEEP", note: "Demo Day sponsor" },
  { en: "KKCompany", zh: "KEEP", note: "Demo Day sponsor" },
  { en: "JBridge", zh: "KEEP", note: "KKCompany tool; switches between OpenAI/Claude/DeepSeek" },
  { en: "Going Cloud", zh: "KEEP", note: "AWS partner booth" },
  { en: "OpenAI", zh: "KEEP" },
  { en: "Claude", zh: "KEEP", note: "Anthropic's AI assistant" },
  { en: "DeepSeek", zh: "KEEP" },
  { en: "GlobalFoundries", zh: "KEEP", note: "Semiconductor foundry; Innowave founder's ex-employer" },
  { en: "NVIDIA", zh: "KEEP" },
  { en: "Intel", zh: "KEEP" },
  { en: "Samsung", zh: "KEEP" },
  { en: "Panasonic", zh: "KEEP" },
  { en: "DHL", zh: "KEEP" },
  { en: "SoftBank", zh: "KEEP" },
  { en: "Levi's", zh: "KEEP", note: "OmniEase customer" },
  { en: "P&G", zh: "KEEP", note: "Procter & Gamble; OmniEase founder's ex-employer" },
  { en: "Hyundai Motors", zh: "KEEP" },
  { en: "GE Aviation", zh: "KEEP" },
  { en: "PETRONAS", zh: "KEEP", note: "Malaysia national oil company; Rosary customer" },
  { en: "TNB", zh: "KEEP", note: "Tenaga Nasional, Malaysia's largest power utility; Rosary customer" },
  { en: "Mobileye", zh: "KEEP", note: "Intel autonomous-driving unit; CLIKA co-founder's ex-employer" },
  { en: "Advantech", zh: "研華", note: "研華科技; CLIKA partner in Taiwan" },
  { en: "Tokio Marine", zh: "KEEP", note: "Novo AI customer (insurer)" },
  { en: "QBE", zh: "KEEP", note: "Novo AI customer (insurer)" },
  { en: "Perpetual Protocol", zh: "KEEP", note: "Taiwan startup; Arrivl founder's ex-employer" },
  { en: "BMW", zh: "KEEP" },
  { en: "Stanford", zh: "KEEP" },
  { en: "Publicis", zh: "KEEP", note: "ad agency; Novo AI founder's ex-employer" },
  { en: "YouTube", zh: "KEEP" },
  { en: "Pizza Hut", zh: "必勝客", note: "Taiwan usage" },
  { en: "Edge AI", zh: "KEEP" },
  { en: "Manufacturing AI", zh: "KEEP", note: "or 製造業 AI" },
  { en: "Go-to-Market", zh: "KEEP", note: "or 進入市場策略; GTM" },
  { en: "GTM", zh: "KEEP", note: "Go-to-Market" },
  { en: "PoC", zh: "KEEP", note: "概念驗證 (proof of concept)" },
  { en: "BIM", zh: "KEEP", note: "Building Information Modeling" },
  { en: "CAD", zh: "KEEP" },
  { en: "AMR", zh: "KEEP", note: "autonomous mobile robot (自主移動機器人)" },
  { en: "unmanned surface vehicle", zh: "無人水面載具", note: "USV" },
  { en: "USV", zh: "KEEP", note: "unmanned surface vehicle (無人水面載具)" },
  { en: "foundation model", zh: "基礎模型", note: "大模型" },
  { en: "industrial foundation model", zh: "工業大模型" },
  { en: "phased array", zh: "相控陣列", note: "Phasetrum's tech" },
  { en: "semiconductor", zh: "半導體" },
  { en: "wafer fab", zh: "晶圓廠" },
  { en: "monthly active users", zh: "月活躍用戶", note: "MAU" },
  // --- from pitch decks (deck jargon, presenters, co-founders); always-on ---
  { en: "Alice Wang", zh: "KEEP", note: "Phasetrum on-stage presenter" },
  { en: "Phase Tuner", zh: "KEEP", note: "Phasetrum's patented phase-control tech" },
  { en: "Beamformer", zh: "KEEP", note: "phased-array beamforming chip" },
  { en: "AIP", zh: "KEEP", note: "Antenna-in-Package (Phasetrum)" },
  { en: "LEO satellite", zh: "低軌衛星" },
  { en: "Telesat", zh: "KEEP", note: "satellite operator" },
  { en: "OneWeb", zh: "KEEP", note: "satellite operator" },
  { en: "C-COM", zh: "KEEP", note: "satellite-terminal partner" },
  { en: "EIRP", zh: "KEEP", note: "RF metric" },
  { en: "Ka band", zh: "KEEP" },
  { en: "Ku band", zh: "KEEP" },
  { en: "MediaTek", zh: "聯發科" },
  { en: "MStar", zh: "晨星", note: "晨星半導體" },
  { en: "NYCU", zh: "陽明交通大學", note: "National Yang Ming Chiao Tung University" },
  { en: "Mike Feng", zh: "KEEP", note: "Innowave co-founder & Head of Solutions; presents the pitch" },
  { en: "iWave", zh: "KEEP", note: "Innowave's Industry Agentic Platform" },
  { en: "IMDA", zh: "KEEP", note: "Infocomm Media Development Authority (Singapore)" },
  { en: "OEE", zh: "KEEP", note: "Overall Equipment Effectiveness" },
  { en: "IDM", zh: "KEEP", note: "Integrated Device Manufacturer (semiconductor)" },
  { en: "Siemens", zh: "KEEP" },
  { en: "McKinsey", zh: "KEEP" },
  { en: "vision AI", zh: "視覺 AI" },
  { en: "Jack", zh: "KEEP", note: "Pathors CEO" },
  { en: "Peter", zh: "KEEP", note: "Pathors CTO" },
  { en: "TSMC", zh: "台積電" },
  { en: "Ander Vallejo", zh: "KEEP", note: "Hyarks CMO" },
  { en: "Nestor Gonzalez", zh: "KEEP", note: "Hyarks CTO" },
  { en: "Kaohsiung", zh: "高雄" },
  { en: "Tri Marine", zh: "KEEP", note: "Hyarks customer (tuna)" },
  { en: "Gilbert Leung", zh: "KEEP", note: "Novo AI CEO & CTO" },
  { en: "medical coding", zh: "醫療編碼" },
  { en: "Devansh Gandhi", zh: "KEEP", note: "Decisions Lab co-founder & CTO" },
  { en: "Almita", zh: "KEEP", note: "Decisions Lab's legal entity, Almita Limited" },
  { en: "HKU", zh: "香港大學", note: "University of Hong Kong" },
  { en: "Charlie", zh: "KEEP", note: "CloudStation's AI agent" },
  { en: "Zakaria Elamdizi", zh: "KEEP", note: "CloudStation CSO" },
  { en: "Driss Assouka", zh: "KEEP", note: "CloudStation CIO" },
  { en: "Ameline Mamin", zh: "KEEP", note: "CloudStation CPO" },
  { en: "governed AI", zh: "KEEP", note: "CloudStation positioning (受治理的 AI)" },
  { en: "Axentel", zh: "KEEP", note: "Jerry Yiu's prior company (acquired)" },
];

// Render the glossary block for the translation system prompt.
export function glossaryForPrompt() {
  return GLOSSARY.map((g) =>
    g.zh === "KEEP"
      ? `- "${g.en}" -> keep as "${g.en}"${g.note ? ` (${g.note})` : ""}`
      : `- "${g.en}" -> "${g.zh}"${g.note ? ` (${g.note})` : ""}`
  ).join("\n");
}
